#!/bin/bash
# NOTE: generated by buildgen.py

CALENDAR_VERSION=$(date '+v%Y_%m_%d')

WINEXE="snore32${CALENDAR_VERSION}.exe"
LINEXE="snore32${CALENDAR_VERSION}.linux"

echo "Building $WINEXE and $LINEXE"
zig cc -s -o "$WINEXE" snore.c -O3 -DCALENDAR_VERSION="\"$CALENDAR_VERSION\"" -target x86-windows-gnu &
zig cc -s -o "$LINEXE" snore.c -O3 -DCALENDAR_VERSION="\"$CALENDAR_VERSION\"" -target x86-linux-musl &
wait

if [ "$1" == "install" ]; then
    echo "installing"
    cp "$WINEXE" /g/mybin/snore.exe
fi
